"""add divination history table

Revision ID: 89cad732c12a
Revises: df2c73988d8d
Create Date: 2022-08-23 18:02:12.164837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89cad732c12a'
down_revision = 'df2c73988d8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('divination', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态: 0 - 显示, 1 - 隐藏'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_create_time'), 'history', ['create_time'], unique=False)
    op.create_index(op.f('ix_history_id'), 'history', ['id'], unique=False)
    op.create_index(op.f('ix_history_location'), 'history', ['location'], unique=False)
    op.create_index(op.f('ix_history_name'), 'history', ['name'], unique=False)
    op.create_index(op.f('ix_history_sex'), 'history', ['sex'], unique=False)
    op.create_index(op.f('ix_history_status'), 'history', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_status'), table_name='history')
    op.drop_index(op.f('ix_history_sex'), table_name='history')
    op.drop_index(op.f('ix_history_name'), table_name='history')
    op.drop_index(op.f('ix_history_location'), table_name='history')
    op.drop_index(op.f('ix_history_id'), table_name='history')
    op.drop_index(op.f('ix_history_create_time'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
